package ro.webdata.echo.translator.edm.lido.commons.constants;

public class PlaceConst {
    public static final String[] RO_COUNTIES = {
            "Alba",
            "Arad",
            "Argeș",
            "Bacău",
            "Bihor",
            "Bistrița-Năsăud",
            "Botoșani",
            "Brașov",
            "Brăila",
            "București",
            "Buzău",
            "Caraș-Severin",
            "Călărași",
            "Cluj",
            "Constanța",
            "Covasna",
            "Dâmbovița",
            "Dolj",
            "Galați",
            "Giurgiu",
            "Gorj",
            "Harghita",
            "Hunedoara",
            "Ialomița",
            "Iași",
            "Ilfov",
            "Maramureș",
            "Mehedinți",
            "Mureș",
            "Neamț",
            "Olt",
            "Prahova",
            "Satu Mare",
            "Sălaj",
            "Sibiu",
            "Suceava",
            "Teleorman",
            "Timiș",
            "Tulcea",
            "Vaslui",
            "Vâlcea",
            "Vrancea"
    };
}
